services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
